[package]
name = "notedeck_notebook"
edition = "2024"
version.workspace = true

[dependencies]
jsoncanvas = { git = "https://github.com/jb55/jsoncanvas", rev = "37a398c4ad42640bd89cd933cf3d6f4c37e9194b" }
notedeck = { workspace = true }
nostrdb = { workspace = true }
rand = { workspace = true }
notedeck_ui = { workspace = true }
egui = { workspace = true }
